### PR TITLE
Add CapsLock functionality by using Capslock + Lshift

### PR DESCRIPTION
**Pull request by AdrianSkar**
Hi! I'm a newbie with both Autohotkey and keymapping but I think this might be helpful for some, it seems to work well for me (pressing Capslock + Lshift to toggle the Caps)

### CODE REVIEW

**Comment by madslundt** [comment]
Thank you for your help.
This will ruin the possibilities for Capslock + Shift + { i, j, k, l }.
A better way would be to something like Capslock + Shift + Space

**Comment by AdrianSkar** [comment]
@madslundt Great, that works perfectly for me. 
Edit: Actually it throws an invalid hotkey error after restarting, I don't know why yet but it seems Autohotkey doesn't support three key combos. I'll try to fix that.

**Comment by AdrianSkar** [comment]
Ok, this seems to be working fine now but can be hard to get used to, as one needs to press the CapsLock key last for it to work and Shift first in order to avoid entering a space character. I haven't found another way to do this yet, would you do it differently or try another shortcut? 
Thank you!

**Comment by AaronRecord** [comment]
I know this PR is old, but what about double tapping caps lock to turn it on (and a single tap would be enough to turn it off)

**Comment by AdrianSkar** [comment]
> 
> 
> I know this PR is old, but what about double tapping caps lock to turn it on (and a single tap would be enough to turn it off)

I think this could be confusing as you could 'need' Caps Lock to be turned on at the same time you use the *arrow* or other functionality.

On the other hand I've been customizing the settings to [my own](https://github.com/AdrianSkar/keybindings) liking and found that triggering it [using both Shift keys](https://github.com/AdrianSkar/keybindings/blob/71f5a70ccbe148fcb0ba84b2fd52ececc74e6ec1/windows/autohotkey/ijkl.ahk#L1) is a likely helpful and common approach.

**Pull request closed without merging**
